name:                eta-ffi-fib
version:             0.1.0.0
github:              "rolandtritsch/eta-ffi-fib"
license:             BSD3
author:              "Roland Tritsch"
maintainer:          "roland@tritsch.org"
copyright:           "2019 Roland Tritsch"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  eta-ffi-fib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eta-ffi-fib

tests:
  eta-ffi-fib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eta-ffi-fib
    - hspec
